/** @type {import('tailwindcss').Config} */
const defaultTheme = require("tailwindcss/defaultTheme");

export default {
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
        "./node_modules/flowbite/**/*.js",
    ],

    theme: {
        extend: {
            fontFamily: {
                body: [
                    "Inter",
                    "ui-sans-serif",
                    "system-ui",
                    "-apple-system",
                    "system-ui",
                    "Segoe UI",
                    "Roboto",
                    "Helvetica Neue",
                    "Arial",
                    "Noto Sans",
                    "sans-serif",
                    "Apple Color Emoji",
                    "Segoe UI Emoji",
                    "Segoe UI Symbol",
                    "Noto Color Emoji",
                ],
                sans: [
                    "Inter",
                    "ui-sans-serif",
                    "system-ui",
                    "-apple-system",
                    "system-ui",
                    "Segoe UI",
                    "Roboto",
                    "Helvetica Neue",
                    "Arial",
                    "Noto Sans",
                    "sans-serif",
                    "Apple Color Emoji",
                    "Segoe UI Emoji",
                    "Segoe UI Symbol",
                    "Noto Color Emoji",
                ],
            },
            colors: {
                primary: {
                    50: "#eff6ff",
                    100: "#dbeafe",
                    200: "#bfdbfe",
                    300: "#93c5fd",
                    400: "#60a5fa",
                    500: "#3b82f6",
                    600: "#2563eb",
                    700: "#1d4ed8",
                    800: "#1e40af",
                    900: "#1e3a8a",
                    950: "#172554",
                },
            },
        },
    },
    plugins: [require("@tailwindcss/forms"), require("flowbite/plugin")],
    safelist: [
        "bg-blue-100",
        "bg-emerald-100",
        "bg-red-100",
        "bg-violet-100",
        "bg-neutral-100",
        "bg-indigo-100",
        "bg-amber-100",
        "hover:bg-blue-200",
        "hover:bg-emerald-200",
        "hover:bg-red-200",
        "hover:bg-violet-200",
        "hover:bg-neutral-200",
        "hover:bg-indigo-200",
        "hover:bg-amber-200",
        "text-blue-800",
        "text-emerald-800",
        "text-red-800",
        "text-violet-800",
        "text-neutral-800",
        "text-indigo-800",
        "text-amber-800",
    ],
};
